apiVersion: v1
items:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: "2019-11-08T11:56:39Z"
    generation: 1
    labels:
      app: quotesapi
    name: quotesapi
    namespace: albert-blazek-bertelsmann-de-quotes-dev
    resourceVersion: "37194525"
    selfLink: /apis/image.openshift.io/v1/namespaces/albert-blazek-bertelsmann-de-quotes-dev/imagestreams/quotesapi
    uid: d2d35d4b-021e-11ea-97a3-0a580a8100f6
  spec:
    lookupPolicy:
      local: false
  status:
    dockerImageRepository: image-registry.openshift-image-registry.svc:5000/albert-blazek-bertelsmann-de-quotes-dev/quotesapi
    publicDockerImageRepository: default-route-openshift-image-registry.apps.ocp-eu1.prod.nextcle.com/albert-blazek-bertelsmann-de-quotes-dev/quotesapi
    tags:
    - items:
      - created: "2019-11-08T11:59:07Z"
        dockerImageReference: image-registry.openshift-image-registry.svc:5000/albert-blazek-bertelsmann-de-quotes-dev/quotesapi@sha256:c4fcf874c7e85e058ac46acefdf03cc45160ea0348398adfdccf9bace962db21
        generation: 1
        image: sha256:c4fcf874c7e85e058ac46acefdf03cc45160ea0348398adfdccf9bace962db21
      tag: latest
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/image.dockerRepositoryCheck: "2019-11-08T11:55:59Z"
    creationTimestamp: "2019-11-08T11:55:59Z"
    generation: 2
    name: quotesdb
    namespace: albert-blazek-bertelsmann-de-quotes-dev
    resourceVersion: "37192811"
    selfLink: /apis/image.openshift.io/v1/namespaces/albert-blazek-bertelsmann-de-quotes-dev/imagestreams/quotesdb
    uid: babd80ff-021e-11ea-8861-0a580a800062
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations: null
      from:
        kind: DockerImage
        name: image-registry.openshift-image-registry.svc:5000/openshift/mysql:5.7
      generation: 2
      importPolicy: {}
      name: "5.7"
      referencePolicy:
        type: Source
  status:
    dockerImageRepository: image-registry.openshift-image-registry.svc:5000/albert-blazek-bertelsmann-de-quotes-dev/quotesdb
    publicDockerImageRepository: default-route-openshift-image-registry.apps.ocp-eu1.prod.nextcle.com/albert-blazek-bertelsmann-de-quotes-dev/quotesdb
    tags:
    - conditions:
      - generation: 2
        lastTransitionTime: "2019-11-08T11:55:59Z"
        message: 'Internal error occurred: Get https://image-registry.openshift-image-registry.svc:5000/v2/:
          x509: certificate signed by unknown authority'
        reason: InternalError
        status: "False"
        type: ImportSuccess
      items: null
      tag: "5.7"
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
